sudo: false
language: android
jdk:
  - oraclejdk8
  
before_install:
  - chmod +x ./SleepCycleAlarm/gradlew
  
install:
- yes | sdkmanager --verbose "build-tools;26.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-28"
- yes | sdkmanager --verbose "extras;android;m2repository"

- yes | sdkmanager --list

script:
  - adb devices
  - ./SleepCycleAlarm/gradlew assembleDebug
