jdk: oraclejdk8
language: android
android: 
  components: 
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-28
    - extra-google-google_play_services

before_install: 
  - "chmod +x ./SleepCycleAlarm/gradlew"
